#!/usr/bin/env python3
"""Write home/.config/zed/keymap.json: Zed's macOS Cmd bindings as Super, then zed/keymap.custom.json."""

import json
import re
import subprocess
import urllib.request
from pathlib import Path

DOTFILES = Path(__file__).resolve().parent.parent
CUSTOM = DOTFILES / "zed" / "keymap.custom.json"
OUTPUT = DOTFILES / "home" / ".config" / "zed" / "keymap.json"
MAC_KEYMAPS = ["default-macos.json", "macos/vscode.json"]


def strip_jsonc(text):
    out, i = [], 0
    while i < len(text):
        if text[i] == '"':
            j = i + 1
            while text[j] != '"':
                j += 2 if text[j] == "\\" else 1
            out.append(text[i : j + 1])
            i = j + 1
        elif text.startswith("//", i):
            while i < len(text) and text[i] != "\n":
                i += 1
        elif text.startswith("/*", i):
            i = text.index("*/", i) + 2
        else:
            out.append(text[i])
            i += 1
    return json.loads(re.sub(r",(\s*[}\]])", r"\1", "".join(out)))


def zed_version():
    output = subprocess.run(["zeditor", "--version"], capture_output=True, text=True, check=True).stdout
    return re.search(r"(\d+\.\d+\.\d+)", output).group(1)


def fetch(version, name):
    url = f"https://raw.githubusercontent.com/zed-industries/zed/v{version}/assets/keymaps/{name}"
    with urllib.request.urlopen(url) as response:
        return strip_jsonc(response.read().decode())


def super_groups(keymap):
    groups = []
    for group in keymap:
        bindings = {
            key.replace("cmd-", "super-"): action
            for key, action in group.get("bindings", {}).items()
            if "cmd-" in key
        }
        if bindings:
            converted = {"context": group["context"]} if "context" in group else {}
            converted["bindings"] = bindings
            groups.append(converted)
    return groups


def main():
    version = zed_version()
    keymap = []
    for name in MAC_KEYMAPS:
        keymap += super_groups(fetch(version, name))
    keymap += strip_jsonc(CUSTOM.read_text())

    header = (
        f"// Generated by zed/build-keymap.py from Zed {version}'s macOS keymaps and zed/keymap.custom.json.\n"
        "// Edit zed/keymap.custom.json and run the script again; changes made here are overwritten.\n"
    )
    OUTPUT.write_text(header + json.dumps(keymap, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {OUTPUT.relative_to(DOTFILES)} from Zed {version}")


if __name__ == "__main__":
    main()
